config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root to: "intranet#dashboard"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  resources :homeworks
  resources :chatrooms, only: [:new, :create, :show, :index]
  get '/intranet/admin/dashboard' => "admin#dashboard", as: :admin_dashboard
  get '/intranet/admin/homework/:id/status' => "admin#homework_status", as: :submissions_status
  get '/intranet/members'
  get '/intranet/members/:id' => "intranet#personal", as: :member
  get '/intranet/dashboard'
  get '/intranet/notice'
  get '/intranet/freeboard'
  get '/intranet/gallery'
  get '/intranet/gallery/new' => "intranet#imgUpload", as: :new_image
  post '/intranet/gallery/new' => "intranet#imgUpload", as: :create_image
  get '/intranet/events', as: :event
  get '/intranet/events/new' => "intranet#newEvent", as: :new_event
  post '/intranet/events/save' => "intranet#createEvent", as: :create_event
  get '/intranet/events/data' => "intranet#getEventJSON", as: :event_json
  get '/intranet/events/:id' => "intranet#viewEvent", as: :view_event
  get '/intranet/events/:id/edit' => "intranet#editEvent", as: :edit_event
  patch '/intranet/events/:id/edit' => "intranet#editEvent", as: :update_event
  delete '/intranet/events/:id/remove' => "intranet#removeEvent", as: :remove_event
  get '/intranet/homework', as: :homework_status
  get '/intranet/homework/:id/submission' => "intranet#submitHomework", as: :submission
  post '/intranet/homework/:id/submission' => "intranet#createSubmission", as: :submit_homework
  patch '/intranet/homework/submission/:id/edit' => "intranet#editSubmission", as: :edit_submission
  get '/intranet/search', as: :search
  get '/intranet/notice/write' => 'intranet#editor', as: :nedit
  get '/intranet/freeboard/write' => 'intranet#editor', as: :fedit
  get '/intranet/post/edit/:id' => "intranet#editPost", as: :pedit
  patch '/intranet/post/edit/:id' => "intranet#editPost", as: :mod_post
  post '/intranet/post/save' => 'intranet#savePost', as: :create_post
  get '/intranet/post/view/:id' => 'intranet#viewPost', as: :view
  post '/intranet/post/view/:id/reply/create' => "intranet#saveReply", as: :replies
  delete '/intranet/post/view/:id/reply/remove' => "intranet#removeReply", as: :remove_reply
  delete '/intranet/post/remove/:id' => "intranet#removePost", as: :remove_post
  delete '/intranet/admin/user/:id' => "admin#removeUser", as: :remove_user
  patch '/intranet/admin/user/:id/accept' => 'admin#acceptUser', as: :accept_user
  patch '/intranet/admin/user/:id/password/reset' => "admin#resetUserPW", as: :reset_password
end

app/controllers/intranet_controller.rb
class IntranetController < ApplicationController
  before_action :authenticate_user!
  before_action :checkAuth, only: [:newEvent]
  
  include ActionView::Helpers::UrlHelper
  
  ## Dashboard
  def dashboard
    @dashboard = "active"
    @title = "Dashboard"
    @recentPost = Post.where(created_at: 1.week.ago..Time.now).order(created_at: :desc)
    @newHomeworks = Homework.where(created_at: 1.week.ago..Time.now).count
    @nonCompletedHomeworks = Homework.all.count - current_user.submissions.count
  end

  # 게시판
  def notice
    @notice = "active"
    @title = "Notice"
    @post = Post.where(category: 1).order(created_at: :desc).page params[:page]
  end

  def freeboard
    @freeboard = "active"
    @title = "Freeboard"
    @post = Post.where(category: 2).order(created_at: :desc).page params[:page]
  end
  
  def viewPost
    @post = Post.find(params[:id])
    @reply = Reply.new
    @replies = @post.replies.order(created_at: :desc).page params[:page]
    if !@post.views.exists?(user_id: current_user.id) then
      @post.views.new(user_id: current_user.id).save
    end
  end
  
  def removePost
    @post = Post.find(params[:id])
    if @post.destroy then
      flash[:removed] = "게시물을 삭제하였습니다."
      case @post.category
      when 1
        redirect_to intranet_notice_path
      when 2
        redirect_to intranet_freeboard_path
      end
    end
  end
  
  def editPost
    @post = Post.find(params[:id])
    if current_user.id != @post.user.id then
      redirectBack
    end
    if request.patch? then
      if @post.update(save_params) then
        flash[:updated] = "게시물을 수정하였습니다."
        redirect_to view_path(@post.id)
      end
    end
  end
  
  def savePost
    post = Post.new(save_params)
    if post.save then
      flash[:saved] = "게시물을 생성하였습니다."
      redirect_to view_path(post.id)
    end
  end
  
  def editor
    if current_page?(nedit_path) then
      checkAuth
    end
    @post = Post.new
  end
  
  # 댓글
  def saveReply
    reply = Reply.new(save_replies)
    if reply.save then
      flash[:saved] = "댓글을 저장하였습니다."
      redirect_to :back
    end
  end
  
  def removeReply
    reply = Reply.find(params[:id])
    if reply.destroy then
      flash[:removed] = "댓글을 삭제하였습니다."
      redirect_to :back
    end
  end

  # 갤러리
  def gallery
    @gallery = "active"
    @title = "Gallery"
    @image = Image.all.order(created_at: :desc).page params[:page]
  end
  
  def imgUpload
    if request.get? then
      @image = Image.new
    elsif request.post? then
      @image = Image.new(save_image)
      if @image.save then
        flash[:saved] = "이미지를 업로드하였습니다."
        redirect_to intranet_gallery_path
      end
    end
  end
  
  # 이벤트
  def events
    @event = "active"
    @title = "EVENT"
  end
  
  def newEvent
    @event = Event.new
  end
  
  def createEvent
    @event = Event.new(save_events)
    @event.end += 1.day
    if @event.save then
      @event.update(url: view_event_path(@event.id))
      flash[:created] = "생성되었습니다."
      redirect_to event_path
    end
  end
  
  def viewEvent
    @event = Event.find(params[:id])
  end
  
  def removeEvent
    @event = Event.find(params[:id])
    if @event.destroy then
      flash[:removed] = "삭제되었습니다."
      redirect_to event_path
    end
  end
  
  def editEvent
    @event = Event.find(params[:id])
    if request.patch? then
      if @event.update(start: params[:event][:start].to_datetime, end: params[:event][:end].to_datetime + 1.day, title: params[:event][:title], content: params[:event][:content]) then
        flash[:updated] = "이벤트를 수정하였습니다."
        redirect_to event_path
      end
    end
  end
  
  def getEventJSON
    if params.has_key?(:search) then
      @query = Event.where("title LIKE ?", "%#{params[:search]}%").or(Event.where("content LIKE ?", "%#{params[:search]}%"))
    elsif params.has_key?(:recent) then
      @query = Event.where(start: Time.now..1.month.from_now)
    else
      @query = Event.all
    end
    respond_to do |format|
      format.json do
        render json: @query.to_json
      end
    end
  end
  
  # 과제
  def homework
    @homework = "active"
    @title = "Homework"
    @homeworks = Homework.all.order(created_at: :desc)
  end
  
  def submitHomework
    @submitted_before = current_user.submissions.exists?(homework_id: params[:id])
    if @submitted_before then
      @submission = current_user.submissions.where(homework_id: params[:id]).first
      @url = edit_submission_path(@submission.id)
    else
      @submission = Submission.new
      @url = submit_homework_path(params[:id])
    end
  end
  
  def createSubmission
    @submission = Submission.new(save_submission)
    if @submission.save then
      flash[:submitted] = "과제를 제출하였습니다."
      redirect_to homework_status_path
    end
  end
  
  def editSubmission
    @submission = Submission.find(params[:submission][:id])
    if @submission.update(save_submission) then
      flash[:submitted] = "과제를 제출하였습니다."
      redirect_to homework_status_path
    end
  end

  # 검색
  def search
    @fromPost = Post.where("title LIKE ?", "%#{params[:keyword]}%").or(Post.where("content LIKE ?", "%#{params[:keyword]}%")) + Post.includes(:user).where("users.name LIKE ?", "%#{params[:keyword]}%").references(:users)
    @fromMembers = User.where("name LIKE ?", "%#{params[:keyword]}%")
    @fromEvents = Event.where("title LIKE ?", "%#{params[:keyword]}%").or(Event.where("content LIKE ?", "%#{params[:keyword]}%"))
    @pictures = Image.where("title LIKE ?", "%#{params[:keyword]}%")
    @fromHomeworks = Homework.where("title LIKE ?", "%#{params[:keyword]}%").or(Homework.where("content LIKE ?", "%#{params[:keyword]}%"))
  end
  
  # 멤버
  def members
    @title = "Members"
    @members = User.all
  end
  
  def personal
    @title = "Member Info"
    @user = User.find(params[:id])
  end
  
  private
  
  def save_params
    params.require(:post).permit(:category, :title, :content, :user_id)
  end
  
  def save_replies
    params.require(:reply).permit(:post_id, :user_id, :content)
  end
  
  def save_events
    params.require(:event).permit(:start, :end, :title, :content)
  end
  
  def save_submission
    params.require(:submission).permit(:homework_id, :user_id, :file)
  end
  
  def save_image
    params.require(:image).permit(:file, :title, :user_id)
  end
  
  def checkAuth
    unless current_user.level == 2 then
      redirectBack
    end
  end
  
  def redirectBack
    flash[:error] = "잘못된 접근입니다."
    redirect_to :back
  end
end

app/helpers/intranet_helper.rb
module IntranetHelper
end

app/views/intranet/dashboard.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>환영합니다! <%= current_user.name %>님</header>
</div>
<div class="content">
    <div class="row">
        <div class="col-lg-6">
            <div class="card card-chart">
                <div class="card-header">
                    <h5 class="card-category">EVENTS</h5>
                    <h4 class="card-title" style="font-weight: 600;">예정 이벤트</h4>
                </div>
                <div class="card-body" style="position: relative;">
                  <div id="calendar"></div>
                  <script>
                      $('#calendar').fullCalendar({ lang: 'ko', themeSystem: 'minty', events: '<%= event_json_path%>.json?recent', maxTime: '24:00:00', height: 500 });
                  </script>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="now-ui-icons fas fa-sync spin"></i> 방금 전 업데이트됨
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card card-chart">
                <div class="card-header">
                    <h5 class="card-category">HOMEWORKS</h5>
                    <h4 class="card-title" style="font-weight: 600;">과제</h4>
                </div>
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-12 col-lg-6">
                      <span class="subtitle">신규과제(1주 내)</span><br>
                      <span class="big"><%= @newHomeworks %></span>건
                    </div>
                    <div class="col-md-12 col-lg-6">
                      <span class="subtitle">미완료과제</span><br>
                      <span class="big"><%= @nonCompletedHomeworks %></span>건
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="now-ui-icons fas fa-sync spin"></i> 방금 전 업데이트 됨
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
      <div class="col-md-12">
          <div class="card">
            <div class="card-header">
                <h5 class="card-category">RECENT POSTS</h5>
                <h4 class="card-title" style="font-weight: 600;">최근 게시물</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                  <table class="table">
                    <thead class="text-primary">
                      <th>
                        구분
                      </th>
                      <th>
                        제목
                      </th>
                      <th>
                        작성자
                      </th>
                      <th>
                        작성일
                      </th>
                    </thead>
                    <tbody>
                      <% Post.where(created_at: 1.week.ago..DateTime.now).each do |p| %>
                      <tr>
                        <td>
                          <% case p.category %>
                          <% when 1 %>
                          공지사항
                          <% when 2 %>
                          자유게시판
                          <% end %>
                        </td>
                        <td>
                          <%= link_to p.title, view_path(p.id) %>
                        </td>
                        <td>
                          <%= link_to p.user.name, member_path(p.user.id) %>
                        </td>
                        <td>
                          <%= p.created_at.strftime("%m/%d") %>
                        </td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
            </div>
          </div>
      </div>
    </div>
</div>

app/views/intranet/editPost.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>게시물 작성</header>
</div>
<div class="content">
    <div class="row">
        <div class="col-12">
            <%= form_for @post, url: mod_post_path, method: :patch do |form| %>
            <% if current_page?(nedit_path) %>
                <%= form.hidden_field :category, value: "1" %>
            <% elsif current_page?(fedit_path) %>
                <%= form.hidden_field :category, value: "2" %>
            <% end %>
            <%= form.hidden_field :user_id, value: current_user.id %>
            <div class="card">
                <div class="card-header">
                    <h5 class="card-category">
                    <% if current_page?(nedit_path) %>
                    NOTICE
                    <% elsif current_page?(fedit_path) %>
                    FREEBOARD
                    <% end %>
                    </h5>
                    <h4 class="card-title" style="font-weight: 600">
                    <% if current_page?(nedit_path) %>
                    공지사항
                    <% elsif current_page?(fedit_path) %>
                    자유게시판
                    <% end %>
                    게시물 편집
                    </h4>
                </div>
                <div class="card-body">
                    <%= form.text_field :title, class: 'title input-text', placeholder: "제목을 입력하세요", autofocus: "on" %>
                    <%= form.label :title, "제목", class: "input-label" %>
                    <%= form.cktext_area :content, cols: 400, ckeditor: { uiColor: '#F2F3F5', height: '60vh' } %>
                </div>
                <div class="card-footer">
                    <%= form.submit "수정", class: "btn btn-primary" %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/intranet/editor.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>게시물 작성</header>
</div>
<div class="content">
    <div class="row">
        <div class="col-12">
            <%= form_for @post, url: create_post_path do |form| %>
            <% if current_page?(nedit_path) %>
                <% if current_user.level == 2 then %>
                <%= form.hidden_field :category, value: "1" %>
                <% else %>
                    <% flash[:error] = "잘못된 접근입니다." %>
                    <% redirect_to :back %>
                <% end %>
            <% elsif current_page?(fedit_path) %>
                <%= form.hidden_field :category, value: "2" %>
            <% end %>
            <%= form.hidden_field :user_id, value: current_user.id %>
            <div class="card">
                <div class="card-header">
                    <h5 class="card-category">
                    <% if current_page?(nedit_path) %>
                    NOTICE
                    <% elsif current_page?(fedit_path) %>
                    FREEBOARD
                    <% end %>
                    </h5>
                    <h4 class="card-title" style="font-weight: 600">
                    <% if current_page?(nedit_path) %>
                    공지사항
                    <% elsif current_page?(fedit_path) %>
                    자유게시판
                    <% end %>
                    게시물 작성
                    </h4>
                </div>
                <div class="card-body">
                    <%= form.text_field :title, class: 'title input-text', placeholder: "제목을 입력하세요", autofocus: "on", required: true %>
                    <%= form.label :title, "제목", class: "input-label" %>
                    <%= form.cktext_area :content, cols: 400, ckeditor: { uiColor: '#F2F3F5', height: '60vh', toolbar: "mini" } %>
                </div>
                <div class="card-footer">
                    <%= form.submit "게시물 생성", class: "btn btn-primary" %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/intranet/events.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>예정된 이벤트</header>
</div>
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-category">EVENTS</h5>
                    <h4 class="card-title" style="font-weight: 600">이벤트</h4>
                </div>
                <div class="card-body">
                    <div id="calendar"></div>
                </div>
                <div class="card-footer">
                    <% if current_user.level == 2 then %>
                        <%= link_to "이벤트 등록", new_event_path, class: "btn btn-primary btn-block" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('#calendar').fullCalendar({ lang: 'ko', themeSystem: 'minty', events: '<%= event_json_path%>.json', maxTime: '24:00:00' });
</script>

app/views/intranet/freeboard.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>자유게시판</header>
</div>
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">FREEBOARD</div>
                <div class="card-body">
                    <% if @post.count == 0 then %>
                    <div class="no-data">
                        <i class="fas fa-exclamation"></i>
                        <h4>게시된 글이 없습니다</h4>
                    </div>
                    <% else %>
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="text-primary">
                                <tr>
                                    <th>No.</th>
                                    <th>제목</th>
                                    <th>작성자</th>
                                    <th>작성일</th>
                                    <th>조회</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @post.each do |p| %>
                                <tr>
                                    <td><%= p.id %></td>
                                    <td><%= link_to p.title, view_path(p.id) %></td>
                                    <td><%= link_to p.user.name, member_path(p.user.id) %></td>
                                    <td><%= p.created_at.strftime("%m/%d %H:%M") %></td>
                                    <td><%= p.views.count %></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                    <% end %>
                </div>
                <div class="card-footer">
                    <%= paginate @post %>
                    <%= link_to "게시물 작성", fedit_path, class: "btn btn-primary btn-block" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/intranet/gallery.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>사진 갤러리</header>
</div>
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">GALLERY</div>
                <div class="card-body">
                    <div class="pics">
                        <div class="row" style="margin: 0 1rem;">
                            <% if @image.count == 0 then %>
                            <div class="no-data col-lg-12">
                                <i class="fas fa-exclamation"></i>
                                <h4>게시된 사진이 없습니다</h4>
                            </div>
                            <% else %>
                            <% @image.each do |image| %>
                            <article class="pic col-md-4 col-lg-6">
                                <%= image_tag image.file %>
                                <hr>
                                <h5 class="title"><%= image.title %></h5>
                                <h6><%= link_to image.user.name, member_path(image.user.id) %></h6>
                            </article>
                            <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <%= paginate @image %>
                    <%= link_to "사진 업로드", new_image_path, class: "btn btn-primary btn-block" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/intranet/homework.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>과제</header>
</div>
<div class="content">
    <div class="row">
        <% if @homeworks.count == 0 then %>
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body no-data">
                    <i class="fas fa-exclamation"></i>
                    <h4>아직 주어진 과제가 없습니다!</h4>
                </div>
            </div>
        </div>
        <% else %>
        <% @homeworks.each do |h| %>
        <div class="col-xs-3 col-sm-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-category">과제 <%= h.id %> | <strong>마감일 <%= h.closing.strftime("%m/%d") %></strong></h5>
                    <h4 class="card-title"><%= h.title %></h4>
                </div>
                <div class="card-body">
                    <%= h.content.html_safe %>
                </div>
                <div class="card-footer">
                   <% if h.closing < Time.now then %>
                   <%= link_to "과제 마감", nil, class: "btn btn-block btn-danger", disabled: true %>
                   <% elsif h.submissions.where(user_id: current_user.id).count < 1 %>
                   <%= link_to "과제 제출", submission_path(h.id), class: "btn btn-block btn-primary" %>
                   <% else %>
                   <%= link_to "과제 수정", submission_path(h.id), class: "btn btn-block btn-info" %>
                   <% end %>
                </div>
            </div>
        </div>
        <% end %>
        <% end %>
    </div>
</div>

app/views/intranet/imgUpload.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>사진 업로드</header>
</div>
<div class="content">
    <div class="row">
        <div class="col-lg-12">
            <%= form_for @image, url: create_image_path, html: { class: "has-file" } do |i| %>
            <%= i.hidden_field :user_id, value: current_user.id %>
            <div class="card">
                <div class="card-header">
                    <h5 class="card-category">UPLOAD IMAGE</h5>
                    <h4 class="card-title" style="font-weight: 600">사진 업로드</h4>
                </div>
                <div class="card-body">
                    <%= i.text_field :title, class: 'title input-text', placeholder: "제목을 입력하세요", autofocus: "on", required: true %>
                    <%= i.label :title, "제목", class: "input-label" %>
                    <div class="filebox">
                        <%= i.file_field :file, class: "inputfile", "data-multiple-caption": " 파일이 선택되었습니다.", accept: 'image/*' %>
                        <label for="image[file]" class="fileTrigger">
                            <figure>
                                <svg xmlns="http://www.w3.org/2000/svg" width="100" height="70" viewBox="0 0 20 17"><path fill="dimgrey" d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"></path></svg>
                            </figure>
                            <span class="desc">클릭하거나 드래그하여 파일을 추가하세요</span>
                        </label>
                        <script>
                            $("input[type=file]").change(function(){
                                if($(this).val()) {
                                    if(['png', 'jpg', 'gif'].indexOf($(this).val().split('.').pop()) < 0) {
                                        swal('파일 형식 오류', '이미지 파일이 아니거나 지원하지 않는 형식입니다.', 'error');
                                        $("span.desc").text("PNG / JPG / GIF 형식만 지원합니다.");
                                        $("input[type=submit]").attr('disabled', true);
                                    } else {
                                        $(".fileTrigger").addClass("selected");
                                        $("span.desc").text($(this).val().split('\\').pop() + $(this).attr('data-multiple-caption'));
                                        $("input[type=submit]").removeAttr('disabled');
                                    }
                                }
                            });
                        </script>
                    </div>
                </div>
                <div class="card-footer">
                    <%= i.submit "업로드", class: "btn btn-primary btn-block" %>
                </div>
            </div
            <% end %>
        </div>
    </div>
</div>

app/views/intranet/members.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>소속 멤버 보기</header>
</div>
<div class="content">
    <div class="row">
        <% @members.each do |member| %>
        <div class="col-md-6 col-lg-4">
            <div class="card card-user">
                <div class="image">
                    <%= image_tag "background.jpg" %>
                </div>
                <div class="card-body">
                    <div class="author">
                        <a href="<%= member_path(member.id) %>">
                            <%= image_tag member.thumb, class:"avatar border-gray" %>
                            <h5 class="title"><%= member.name %></h5>
                        </a>
                        <p class="description">
                            <%= member.email %>
                        </p>
                    </div>
                    <p class="description text-center">
                        <%= member.introduction %>
                    </p>
                </div>
            </div> 
        </div>
        <% end %>
    </div>
</div>

app/views/intranet/personal.html.erb
<div class="panel-header panel-header-lg center-header">
    <header><%= @user.name %></header>
</div>
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card card-user">
                <div class="image">
                    <%= image_tag "background.jpg" %>
                </div>
                <div class="card-body">
                    <div class="author">
                        <%= image_tag @user.thumb, class:"avatar border-gray" %>
                        <h5 class="title"><%= @user.name %></h5>
                        <p class="description">
                            <%= @user.email %>
                        </p>
                    </div>
                    <p class="description text-center">
                        <%= @user.introduction %>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/intranet/viewEvent.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>이벤트 보기</header>
</div>
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-category">Event</h5>
                    <h4 class="card-title" style="font-weight: 600;"><%= @event.title %></h4>
                </div>
                <div class="card-body">
                    <h5 style="display: inline;"><%= @event.start.strftime("%Y-%m-%d") %></h5>부터 <h5 style="display: inline;"><%= (@event.end - 1.day).strftime("%Y-%m-%d") %></h5>까지
                    <hr>
                    <%= @event.content.html_safe %>
                </div>
                <div class="card-footer">
                    <hr>
                    <%= link_to "목록", event_path, class: "btn btn-info" %>
                    <% if current_user.level == 2 then %>
                    <%= link_to "이벤트 수정", edit_event_path(@event.id), class: "btn btn-warning" %>
                    <%= link_to "이벤트 삭제", remove_event_path(@event.id), class: "btn btn-danger", "data-method": "DELETE", "data-confirm": "삭제하시겠습니까? 삭제된 데이터는 복구가 불가합니다." %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/intranet/viewPost.html.erb
<div class="panel-header panel-header-lg center-header">
    <header>게시물 보기</header>
</div>
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-category text-right">
                        <% case @post.category %>
                        <% when 1 %>
                        공지사항 | 게시번호 <%= @post.id %> | 게시일자 <%= @post.created_at.strftime("%m/%d") %> | 조회수 <%= @post.views.count %>
                        <% when 2 %>
                        자유게시판 | 게시번호 <%= @post.id %> | 게시일자 <%= @post.created_at.strftime("%m/%d") %> | 조회수 <%= @post.views.count %>
                        <% end %>
                    </h5>
                    <h4 class="card-title" style="font-weight: 600;">
                        <%= @post.title %>
                    </h4>
                </div>
                <div class="card-body" style="min-height: 50vh">
                    <%= @post.content.html_safe %>
                </div>
                <div class="card-footer">
                    <% case @post.category %>
                    <% when 1 %>
                    <%= link_to "목록", intranet_notice_path, class: "btn btn-info" %>
                    <% when 2 %>
                    <%= link_to "목록", intranet_freeboard_path, class: "btn btn-info" %>
                    <% end %>
                    <% if @post.user.id == current_user.id then %>
                        <%= link_to "편집", pedit_path(@post.id), class: "btn btn-warning" %>
                        <%= link_to "삭제", remove_post_path(@post.id), class: "btn btn-primary", "data-method": "DELETE", "data-confirm": "삭제하시겠습니까? 삭제 시, 복구가 불가능합니다." %>
                    <% end %>
                    <hr>
                    <%= render 'templates/reply' %>
                </div>
            </div>
        </div>
    </div>
</div>