config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root to: "intranet#dashboard"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  resources :homeworks
  resources :chatrooms, only: [:new, :create, :show, :index]
  get '/intranet/admin/dashboard' => "admin#dashboard", as: :admin_dashboard
  get '/intranet/admin/homework/:id/status' => "admin#homework_status", as: :submissions_status
  get '/intranet/members'
  get '/intranet/members/:id' => "intranet#personal", as: :member
  get '/intranet/dashboard'
  get '/intranet/notice'
  get '/intranet/freeboard'
  get '/intranet/gallery'
  get '/intranet/gallery/new' => "intranet#imgUpload", as: :new_image
  post '/intranet/gallery/new' => "intranet#imgUpload", as: :create_image
  get '/intranet/events', as: :event
  get '/intranet/events/new' => "intranet#newEvent", as: :new_event
  post '/intranet/events/save' => "intranet#createEvent", as: :create_event
  get '/intranet/events/data' => "intranet#getEventJSON", as: :event_json
  get '/intranet/events/:id' => "intranet#viewEvent", as: :view_event
  get '/intranet/events/:id/edit' => "intranet#editEvent", as: :edit_event
  patch '/intranet/events/:id/edit' => "intranet#editEvent", as: :update_event
  delete '/intranet/events/:id/remove' => "intranet#removeEvent", as: :remove_event
  get '/intranet/homework', as: :homework_status
  get '/intranet/homework/:id/submission' => "intranet#submitHomework", as: :submission
  post '/intranet/homework/:id/submission' => "intranet#createSubmission", as: :submit_homework
  patch '/intranet/homework/submission/:id/edit' => "intranet#editSubmission", as: :edit_submission
  get '/intranet/search', as: :search
  get '/intranet/notice/write' => 'intranet#editor', as: :nedit
  get '/intranet/freeboard/write' => 'intranet#editor', as: :fedit
  get '/intranet/post/edit/:id' => "intranet#editPost", as: :pedit
  patch '/intranet/post/edit/:id' => "intranet#editPost", as: :mod_post
  post '/intranet/post/save' => 'intranet#savePost', as: :create_post
  get '/intranet/post/view/:id' => 'intranet#viewPost', as: :view
  post '/intranet/post/view/:id/reply/create' => "intranet#saveReply", as: :replies
  delete '/intranet/post/view/:id/reply/remove' => "intranet#removeReply", as: :remove_reply
  delete '/intranet/post/remove/:id' => "intranet#removePost", as: :remove_post
  delete '/intranet/admin/user/:id' => "admin#removeUser", as: :remove_user
  patch '/intranet/admin/user/:id/accept' => 'admin#acceptUser', as: :accept_user
  patch '/intranet/admin/user/:id/password/reset' => "admin#resetUserPW", as: :reset_password
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ko">
<head>
  <%= csrf_meta_tags %>
  <title>LIKELION :: 아주대학교 인트라넷</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
  <link href="//cdn.jsdelivr.net/font-kopub/1.0/kopubdotum.css" rel="stylesheet">
  <link href="//use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag Ckeditor.cdn_url %>
</head>
<body style="background: #ebecf1;">
    <div class="loader">
        <svg class="lds-coolors" width="10rem"  height="10rem"  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style=""><defs>
         <mask id="coolors-0.2e4a635a676849">
           <circle cx="50" cy="50" r="20" stroke="#fff" stroke-linecap="round" stroke-dasharray="94.24777960769379 31.41592653589793" stroke-width="10" transform="rotate(216 50 50)">
             <animateTransform attributeName="transform" type="rotate" values="0 50 50;360 50 50" times="0;1" dur="1s" repeatCount="indefinite"></animateTransform>
           </circle>
         </mask>
        </defs>
        <g mask="url(#coolors-0.2e4a635a676849)"><rect x="19.5" y="0" width="13" height="100">
          <animate attributeName="fill" values="#e15b64;#f47e60;#f8b26a;#abbd81;#849b87" times="0;0.25;0.5;0.75;1" dur="1s" repeatCount="indefinite" begin="-0.8s"></animate>
            </rect><rect x="31.5" y="0" width="13" height="100">
              <animate attributeName="fill" values="#e15b64;#f47e60;#f8b26a;#abbd81;#849b87" times="0;0.25;0.5;0.75;1" dur="1s" repeatCount="indefinite" begin="-0.6s"></animate>
            </rect><rect x="43.5" y="0" width="13" height="100">
              <animate attributeName="fill" values="#e15b64;#f47e60;#f8b26a;#abbd81;#849b87" times="0;0.25;0.5;0.75;1" dur="1s" repeatCount="indefinite" begin="-0.4s"></animate>
            </rect><rect x="55.5" y="0" width="13" height="100">
              <animate attributeName="fill" values="#e15b64;#f47e60;#f8b26a;#abbd81;#849b87" times="0;0.25;0.5;0.75;1" dur="1s" repeatCount="indefinite" begin="-0.2s"></animate>
            </rect><rect x="67.5" y="0" width="13" height="100">
              <animate attributeName="fill" values="#e15b64;#f47e60;#f8b26a;#abbd81;#849b87" times="0;0.25;0.5;0.75;1" dur="1s" repeatCount="indefinite" begin="0s"></animate>
            </rect>
        </g>
        </svg>
    </div>
    <div class="wrapper">
      <div class="sidebar" data-color="<%= ['blue', 'orange', 'red'].sample %>">
            <div class="logo">
                <a href="http://ajou.likelion.org" class="simple-text logo-mini">
                    AU
                </a>
                <a href="/" class="simple-text logo-normal">
                    <%= image_tag "https://likelion.net/assets/logo/likelion-white-a930fbcdf3042a50ba882ece9c02f43536971297a8e143e212d9b92d653bfa44.png", style: "height: 20px" %>
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="<%= @dashboard %>">
                        <a href="<%= intranet_dashboard_path %>">
                            <i class="fas fa-inbox"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li class="<%= @notice %>">
                        <a href="<%= intranet_notice_path %>">
                            <i class="fas fa-book"></i>
                            <p>공지사항</p>
                        </a>
                    </li>
                    <li class="<%= @freeboard %>">
                        <a href="<%= intranet_freeboard_path %>">
                            <i class="fas fa-book"></i>
                            <p>자유게시판</p>
                        </a>
                    </li>
                    <li class="<%= @homework %>">
                        <a href="<%= homework_status_path %>">
                            <i class="fas fa-sticky-note"></i>
                            <p>과제</p>
                        </a>
                    </li>
                    <li class="<%= @event %>">
                        <a href="<%= event_path %>">
                            <i class="far fa-calendar-alt"></i>
                            <p>이벤트</p>
                        </a>
                    </li>
                    <li class="<%= @gallery %>">
                        <a href="<%= intranet_gallery_path %>">
                            <i class="far fa-image"></i>
                            <p>사진</p>
                        </a>
                    </li>
                    <% if current_user.level == 2 then %>
                    <li class="<%= @admin %>">
                        <a href="<%= admin_dashboard_path %>">
                            <i class="far fa-user"></i>
                            <p>운영진</p>
                        </a>
                    </li>
                    <% end %>
                </ul>
            </div>
        </div>
      <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute bg-primary fixed-top">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <a class="navbar-brand" href=""><%= @title %></a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navigation">
                    <form method="GET" action="<%= search_path %>">
                        <div class="input-group no-border">
                            <input type="text" name="keyword" class="form-control" placeholder="검색">
                            <span class="input-group-addon">
                                <i class="fas fa-search"></i>
                            </span>
                        </div>
                    </form>
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-user"></i>
                                <p>
                                    <span class="d-lg-none d-md-block">계정</span>
                                </p>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <%= link_to "정보 변경", edit_user_registration_path, class: "dropdown-item" %>
                                <%= link_to "소속 멤버 보기", intranet_members_path, class: "dropdown-item" %>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-method="DELETE" href="<%= destroy_user_session_path %>">
                                <i class="fas fa-key"></i>
                                <p>
                                    <span class="d-lg-none d-md-block">로그아웃</span>
                                </p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Navbar -->
        <%= yield %>
        
        <footer class="footer">
            <div class="container-fluid">
                <nav>
                    <ul>
                        <li>
                            <a href="http://likelion.org">
                                LIKELION
                            </a>
                        </li>
                        <li>
                            <a href="http://aulikelion.github.io">
                                아주대학교 멋쟁이사자처럼
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright">
                    &copy;
                    <script>
                        document.write(new Date().getFullYear())
                    </script>, Organization by
                    <a href="http://www.likelion.org" target="_blank">LIKELION</a>. Coded by J.W.Jeon (4th).
                </div>
            </div>
        </footer>
      </div>
    </div>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert2@7.15.0/dist/sweetalert2.all.js"></script>
    <% if !flash.empty? then %>
    <script>
        <% flash.keys.each do |f| %>
        <% if f == 'error' then %>
        swal('<%= f.capitalize %>', '<%= flash[f] %>', 'error');
        <% else %>
        swal('<%= f.capitalize %>', '<%= flash[f] %>', 'success');
        <% end %>
        <% end %>
    </script>
    <% end %>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCUMENT html>
<html lang="ko">
    <head>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
        <title>LIKELION :: 아주대학교 인트라넷</title>
        <link href="https://cdn.rawgit.com/filipelinhares/ress/master/dist/ress.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/font-kopub/1.0/kopubdotum.css" rel="stylesheet">
        <%= stylesheet_link_tag "login", "data-turbolinks-track": false %>
        <%= javascript_include_tag "login", "data-turbolinks-track": false %>
    </head>
    <body>
        <div class="cover"></div>
        <div class="valign-wrapper">
            <header>
                <div class="likelion">LIKELION</div>
                <h1>멋쟁이사자처럼<br>인트라넷<br>(아주대학교)</h1>
                <footer>LIKELION</footer>
            </header>
            <%= yield %>
        </div>
    </body>
</html>